# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ms_faceRecognition.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18ms_faceRecognition.proto\"\x94\x01\n\x16\x46\x61\x63\x65RecognitionRequest\x12\r\n\x05image\x18\x01 \x01(\x0c\x12\x39\n\tpersonBox\x18\x02 \x03(\x0b\x32&.FaceRecognitionRequest.PersonBoxEntry\x1a\x30\n\x0ePersonBoxEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\"\x8f\x01\n\x1d\x46\x61\x63\x65RecognitionInferenceReply\x12\x11\n\x04uuid\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x18\n\x0b\x66\x61\x63\x65\x43\x65nterX\x18\x02 \x01(\x05H\x01\x88\x01\x01\x12\x18\n\x0b\x66\x61\x63\x65\x43\x65nterY\x18\x03 \x01(\x05H\x02\x88\x01\x01\x42\x07\n\x05_uuidB\x0e\n\x0c_faceCenterXB\x0e\n\x0c_faceCenterY2_\n\x15\x46\x61\x63\x65RecognitionServer\x12\x46\n\tinference\x12\x17.FaceRecognitionRequest\x1a\x1e.FaceRecognitionInferenceReply\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ms_faceRecognition_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FACERECOGNITIONREQUEST_PERSONBOXENTRY._options = None
  _FACERECOGNITIONREQUEST_PERSONBOXENTRY._serialized_options = b'8\001'
  _FACERECOGNITIONREQUEST._serialized_start=29
  _FACERECOGNITIONREQUEST._serialized_end=177
  _FACERECOGNITIONREQUEST_PERSONBOXENTRY._serialized_start=129
  _FACERECOGNITIONREQUEST_PERSONBOXENTRY._serialized_end=177
  _FACERECOGNITIONINFERENCEREPLY._serialized_start=180
  _FACERECOGNITIONINFERENCEREPLY._serialized_end=323
  _FACERECOGNITIONSERVER._serialized_start=325
  _FACERECOGNITIONSERVER._serialized_end=420
# @@protoc_insertion_point(module_scope)
